# Generated by Django 3.2.18 on 2023-04-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
    ]
