# Generated by Django 3.2.18 on 2023-04-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user',
            new_name='user1',
        ),
    ]
