# Generated by Django 3.2.18 on 2023-04-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_signup_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='pass1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user1',
            new_name='us1',
        ),
    ]
