# Generated by Django 3.2.18 on 2023-04-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230423_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
